FROM cschranz/gpu-jupyter:v1.10_cuda-12.9_ubuntu-24.04_python-only
USER root
RUN apt-get update && apt-get install -y \
    git \
    curl \
    build-essential \
    libpq-dev \
    && apt-get clean && rm -rf /var/lib/apt/lists/*
COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/
USER jovyan
WORKDIR /home/jovyan